export 'package:audio_player/widgets/custom_button.dart';
export 'package:audio_player/widgets/fading_indicator.dart';
export 'package:animate_gradient/animate_gradient.dart';
export 'package:audio_player/widgets/ui_properties.dart';
export 'package:audio_player/widgets/size_text_modifiers.dart';
export 'package:audio_player/widgets/page_animation.dart';
export 'package:audio_player/widgets/responsive_widgets/responsive_widget.dart';
export 'package:audio_player/widgets/responsive_widgets/hovered_widget.dart';
export 'package:audio_player/widgets/get_it_dependencies/get_it_dependencies.dart';
