// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgeXNI6HIYVdF6mNFJsG30DmO2sQwEGkQ',
    appId: '1:506290258387:web:0b6aa690057a2d3a2eef26',
    messagingSenderId: '506290258387',
    projectId: 'fir-hw-68f87',
    authDomain: 'fir-hw-68f87.firebaseapp.com',
    storageBucket: 'fir-hw-68f87.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTIGRaz9Un_y_IfPEBasJdTtCTXwTapxU',
    appId: '1:506290258387:android:2415e8ca390c825d2eef26',
    messagingSenderId: '506290258387',
    projectId: 'fir-hw-68f87',
    storageBucket: 'fir-hw-68f87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ygtsZZlpV9W23dvQ1myjgQ3G3GJDB7Y',
    appId: '1:506290258387:ios:f58ed6f4951e8b662eef26',
    messagingSenderId: '506290258387',
    projectId: 'fir-hw-68f87',
    storageBucket: 'fir-hw-68f87.appspot.com',
    iosClientId: '506290258387-t5npurq9a2jkgpkd1j3kg6t7o5aeirp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ygtsZZlpV9W23dvQ1myjgQ3G3GJDB7Y',
    appId: '1:506290258387:ios:db71055d209353712eef26',
    messagingSenderId: '506290258387',
    projectId: 'fir-hw-68f87',
    storageBucket: 'fir-hw-68f87.appspot.com',
    iosClientId: '506290258387-n28if9et6r92892m5ihpl39gpk5lv689.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
