// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2vVCCLgBFhX-dficY6xrxaI_gm6XE8a8',
    appId: '1:905413251174:web:cbe113cfa396a4ff4adda7',
    messagingSenderId: '905413251174',
    projectId: 'finalproject-74eb0',
    authDomain: 'finalproject-74eb0.firebaseapp.com',
    storageBucket: 'finalproject-74eb0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuXdLVaUiqCcQkynsRpKTjssgD1qsBHaY',
    appId: '1:905413251174:android:74b4a8cb0a3d498c4adda7',
    messagingSenderId: '905413251174',
    projectId: 'finalproject-74eb0',
    storageBucket: 'finalproject-74eb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdX0YQYKWDkDjgHa2BCAMi_qm307Tzwnk',
    appId: '1:905413251174:ios:68682bb7d6d9688b4adda7',
    messagingSenderId: '905413251174',
    projectId: 'finalproject-74eb0',
    storageBucket: 'finalproject-74eb0.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdX0YQYKWDkDjgHa2BCAMi_qm307Tzwnk',
    appId: '1:905413251174:ios:d2eb9077b33cef1f4adda7',
    messagingSenderId: '905413251174',
    projectId: 'finalproject-74eb0',
    storageBucket: 'finalproject-74eb0.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
